import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  cookbook: [
    {
      type: 'category',
      label: 'Статьи',
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'cookbook/articles' }],
    },
  ],
};

export default sidebars;
